ALTER TABLE ROLEJO.TIPO_CUENTA
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROLEJO.TIPO_CUENTA CASCADE CONSTRAINTS;

CREATE TABLE ROLEJO.TIPO_CUENTA
(
  ID_TIPO_CUENTA  NUMBER                        NOT NULL,
  NOMBRE          VARCHAR2(50 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE ROLEJO.USUARIO
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROLEJO.USUARIO CASCADE CONSTRAINTS;

CREATE TABLE ROLEJO.USUARIO
(
  ID_USUARIO      NUMBER                        NOT NULL,
  NOMBRES         VARCHAR2(50 BYTE)             NOT NULL,
  APELLIDOS       VARCHAR2(50 BYTE)             NOT NULL,
  DNI             VARCHAR2(15 BYTE)             NOT NULL,
  PASSWORD        VARCHAR2(50 BYTE)             NOT NULL,
  EMAIL           VARCHAR2(50 BYTE),
  FECHA_CREACION  DATE                          NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ROLEJO.TIPO_CUENTA_PK ON ROLEJO.TIPO_CUENTA
(ID_TIPO_CUENTA)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX ROLEJO.USUARIO_PK ON ROLEJO.USUARIO
(ID_USUARIO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE ROLEJO.PRODUCTO
 DROP PRIMARY KEY CASCADE;

DROP TABLE ROLEJO.PRODUCTO CASCADE CONSTRAINTS;

CREATE TABLE ROLEJO.PRODUCTO
(
  ID_PRODUCTO          NUMBER                   NOT NULL,
  ID_TIPO_CUENTA       NUMBER,
  NUMERO_CUENTA        VARCHAR2(50 BYTE)        NOT NULL,
  VERIFICACION_CUENTA  VARCHAR2(50 BYTE)        NOT NULL,
  SALDO                FLOAT(126)               NOT NULL,
  FECHA_CREACION       DATE                     NOT NULL,
  ID_USUARIO           NUMBER                   NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ROLEJO.PRODUCTO_PK ON ROLEJO.PRODUCTO
(ID_PRODUCTO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE ROLEJO.TIPO_CUENTA ADD (
  CONSTRAINT TIPO_CUENTA_PK
  PRIMARY KEY
  (ID_TIPO_CUENTA)
  USING INDEX ROLEJO.TIPO_CUENTA_PK
  ENABLE VALIDATE);

ALTER TABLE ROLEJO.USUARIO ADD (
  CONSTRAINT USUARIO_PK
  PRIMARY KEY
  (ID_USUARIO)
  USING INDEX ROLEJO.USUARIO_PK
  ENABLE VALIDATE);

ALTER TABLE ROLEJO.PRODUCTO ADD (
  CONSTRAINT PRODUCTO_PK
  PRIMARY KEY
  (ID_PRODUCTO)
  USING INDEX ROLEJO.PRODUCTO_PK
  ENABLE VALIDATE);

ALTER TABLE ROLEJO.PRODUCTO ADD (
  CONSTRAINT PRODUCTO_USUARIO 
  FOREIGN KEY (ID_USUARIO) 
  REFERENCES ROLEJO.USUARIO (ID_USUARIO)
  ENABLE VALIDATE);
